### PR TITLE
Use FUIAuthPickerViewController like RootViewController

### LINKED ISSUE #254: Use FUIAuthPickerViewController like RootViewController of the application
### Environment

  * Objective C or Swift: Swift
  * iOS version: 10.0
  * Firebase SDK version: 3.14.0
  * FirebaseUI version: 3.1.0
  * CocoaPods Version: 1.0
  
### Step 3: Describe the problem:
All the callbacks are in the completion block of the dismiss method of the navigation controller, which does not allow to use `FUIAuthPickerViewController` like RootViewController 
I think we should separate callBack and dismiss actions, and we should not dismiss the controller 
if the user implement the protocol, Like [UIImagepickercontroller](https://developer.apple.com/reference/uikit/uiimagepickercontroller)

#### Steps to reproduce:
  1. Use `FUIAuthPickerViewController` as root view controller of the application 
  
#### Observed Results:
  * The callbacks are not received 
  
#### Expected Results:
  * We should receive the callbacks

### PR DESCRIPTION
**Pull request by najdanovicivan**
Fix #254 - If authViewController is set as the rootViewController delegate will be called without dismissing the view.

### CODE REVIEW

File: FirebaseAuthUI/FUIAuthBaseViewController.m [hunk 1]
```diff
@@ -276,6 +276,16 @@ - (void)pushViewController:(UIViewController *)viewController {
               navigationController:self.navigationController];
 }
 
+- (void)dismissNavigationControllerAnimated:(BOOL)animated completion:(void (^)(void))completion{
+     if (self.navigationController.presentingViewController == nil){
+         if (completion){
+             completion();
+         }
+     }else{
```
Comment (morganchen12) [inline FirebaseAuthUI/FUIAuthBaseViewController.m]: nit: spaces between else and braces

`} else {`

File: FirebaseAuthUI/FUIAuthBaseViewController.m [hunk 2]
```diff
@@ -276,6 +276,16 @@ - (void)pushViewController:(UIViewController *)viewController {
               navigationController:self.navigationController];
 }
 
+- (void)dismissNavigationControllerAnimated:(BOOL)animated completion:(void (^)(void))completion{
```
Comment (morganchen12) [inline FirebaseAuthUI/FUIAuthBaseViewController.m]: nit: space between completion and curly brace

`completion  {`

File: FirebaseAuthUI/FUIPasswordSignUpViewController.m [hunk 3]
```diff
@@ -223,8 +223,8 @@ - (void)finishSignUpWithAuthDataResult:(nullable FIRAuthDataResult *)authDataRes
         return;
     }
   }
-
-  [self.navigationController dismissViewControllerAnimated:YES completion:^() {
+
```
Comment (morganchen12) [inline FirebaseAuthUI/FUIPasswordSignUpViewController.m]: nit: remove trailing whitespace

**Comment by najdanovicivan** [comment]
Any ETA when this will be merged ?

**Comment by najdanovicivan** [comment]
Fixed, you can merge it now.

**Comment by morganchen12** [comment]
Thanks!

**Comment by StefanICT** [comment]
@morganchen12 Currently struggling with this as well and this will fix my problem. When will this be released?

**Comment by morganchen12** [comment]
I'll cut a release by the end of this week.

**Comment by StefanICT** [comment]
@morganchen12 Thank you!

**Comment by najdanovicivan** [comment]
@morganchen12 Any ETA on the release including those changes ?

**Comment by morganchen12** [comment]
This has been released.
