### PR TITLE
Fix missing text input trait

### LINKED ISSUE #775: OTP not fill in PhoneAuth
I am using the FirebaseUI for Phone Auth. OTP message does not fill the keyboard autofill suggestion box. OTP Code fill view (FUICodeField) does not appear the suggestion box in a keyboard. I have shared the screenshot link for this issue.
firebase-auth

Please help me to resolve this issue.

Env:
Lib: Firebase (v6.8.1), FirebaseAuth (v6.2.3), FirebaseCore (v6.2.3) and FirebaseUI (v8.1.0). 
Deployment Target set to iOS 12.3.
iPhone 6 (v12.4.1).

_Originally posted by @naveengoyal1993 in https://github.com/firebase/FirebaseUI-iOS/issues/515#issuecomment-533486382_

### PR DESCRIPTION
**Pull request by morganchen12**
Fixes #775.

### CODE REVIEW

File: PhoneAuth/FirebasePhoneAuthUI/FUICodeField.m [hunk 1]
```diff
@@ -179,6 +186,10 @@ - (UITextContentType _Null_unspecified)textContentType {
   return nil;
 }
 
+- (void)setTextContentType:(_Null_unspecified UITextContentType)textContentType {
```
Comment (renkelvin) [inline PhoneAuth/FirebasePhoneAuthUI/FUICodeField.m]: Could you explain more how this fix the issue? why using _Null_unspecified

Comment (morganchen12) [reply PhoneAuth/FirebasePhoneAuthUI/FUICodeField.m]: This doesn't fix the issue, it just conforms better to the protocol since the `textContentType` property is not readonly.

Comment (renkelvin) [reply PhoneAuth/FirebasePhoneAuthUI/FUICodeField.m]: Does it fix #775?

Comment (morganchen12) [reply PhoneAuth/FirebasePhoneAuthUI/FUICodeField.m]: The fix is in lines 62-68.

Comment (renkelvin) [reply PhoneAuth/FirebasePhoneAuthUI/FUICodeField.m]: Yeah, sounds good. I understand it now.

**Comment by dtran320** [comment]
Awesome! Thanks so much @morganchen12! Would it be possible for y'all to cut a new release with this, or what does your normal release schedule look like?

**Comment by morganchen12** [comment]
The fix will be released this week, today or tomorrow.
